# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-25 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationloginapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdata',
            old_name='number',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='registrationdata',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='username',
        ),
    ]
